[package]
name = "swagger-ui"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
keywords.workspace = true
readme.workspace = true
authors.workspace = true

[dependencies]

[lints]
workspace = true
